services:
  database:
    image: postgres:14.4
    restart: always
    environment:
      POSTGRES_USER: example
      POSTGRES_PASSWORD: example
    volumes:
      - /ESGdata:/var/lib/postgresql/data
    ports:
      - "5432:5432"
    #shm_size: 512mb

  grafana:
    depends_on:
      - database
    image: grafana/grafana:8.5.13
    ports:
      - 3000:3000
    user: ":"
    volumes:
    - /grafana:/var/lib/grafana
    - ./configs/provisioning:/etc/grafana/provisioning
    - ./configs/provisioning/dashboards:/var/lib/grafana/dashboards

  selenium:
    image: selenium/standalone-firefox
    ports:
    - 4444:4444

  script:
    depends_on:
      - database
    build: api
    environment:
      DATABASE_URL: "postgresql+psycopg2://example:example@database/database"
    ports:
      - 8000:8000

  parsers:
    depends_on:
      - script
      - database
      - selenium
    build: parser
    environment:
      DATABASE_URL: "postgresql+psycopg2://example:example@database/parser"
      DOCKER: "true"
      API_URL: "http://script:8000"
