services:
  database:
    image: postgres:14.4
    restart: always
    env_file:
      - .env
    volumes:
      - /ESGdata:/var/lib/postgresql/data
    ports:
      - "5432:5432"
    #shm_size: 512mb

  grafana:
    depends_on:
      - database
    image: grafana/grafana:8.5.13
    ports:
      - 3000:3000
    user: ":"
    volumes:
    - /grafana:/var/lib/grafana
    - ./configs/provisioning:/etc/grafana/provisioning
    - ./configs/provisioning/dashboards:/var/lib/grafana/dashboards

  selenium-hub:
    image: selenium/hub:4.5
    container_name: selenium-hub
    ports:
      - 4442:4442
      - 4443:4443
      - 4444:4444
      - 7900:7900  # to view browsers

  firefox:
    image: selenium/node-firefox:105.0
    depends_on:
      - selenium-hub
    env_file:
      - .env

  api:
    depends_on:
      - database
    build: api
    env_file:
      - .env
    environment:
      POSTGRES_DB: "database"
    ports:
      - 8000:8000

  sravni-reviews-parser:
    depends_on:
      - api
    build: parser
    env_file:
      - .env
    command: ["python", "main.py", "--site", "sravni_reviews"]
    environment:
      POSTGRES_DB: "sravni"

  sravni-mfo-reviews-parser:
    depends_on:
      - api
    build: parser
    env_file:
      - .env
    command: [ "python", "main.py", "--site", "sravni_mfo_reviews" ]
    environment:
      POSTGRES_DB: "sravni_mfo"

  sravni-insurance-reviews-parser:
    depends_on:
      - api
    build: parser
    env_file:
      - .env
    command: ["python", "main.py", "--site", "sravni_insurance_reviews"]
    environment:
      POSTGRES_DB: "sravni_insurance"

  banki-reviews-parser:
    depends_on:
      - api
    build: parser
    env_file:
      - .env
    command: ["python", "main.py", "--site", "banki_reviews"]
    environment:
      POSTGRES_DB: "banki"

  banki-news-parser:
    depends_on:
      - api
    build: parser
    env_file:
      - .env
    command: [ "python", "main.py", "--site", "banki_news" ]
    environment:
      POSTGRES_DB: "banki"

  banki-insurance-parser:
    depends_on:
      - api
    build: parser
    env_file:
      - .env
    command: [ "python", "main.py", "--site", "banki_insurance" ]
    environment:
      POSTGRES_DB: "banki_insurance"

  banki-mfo-parser:
    depends_on:
      - api
    build: parser
    env_file:
      - .env
    command: [ "python", "main.py", "--site", "banki_mfo" ]
    environment:
      POSTGRES_DB: "banki_mfo"

  banki-broker-parser:
    depends_on:
      - api
    build: parser
    env_file:
      - .env
    command: [ "python", "main.py", "--site", "banki_broker" ]
    environment:
      POSTGRES_DB: "banki_broker"

  vk-comments-parser:
    depends_on:
      - api
    build: parser
    env_file:
      - .env
    command: ["python", "main.py", "--site", "vk_comments"]
    environment:
      POSTGRES_DB: "vk_comments"

  vk-other-comments-parser:
    depends_on:
      - api
    build: parser
    env_file:
      - .env
    command: [ "python", "main.py", "--site", "vk_other" ]
    environment:
      POSTGRES_DB: "vk_other"

  irecommend-reviews-parser:
    depends_on:
      - api
      - selenium-hub
    build: parser
    command: [ "python", "main.py", "--site", "irecommend_reviews" ]
    environment:
      POSTGRES_DB: "irecommend_reviews"

  views:
    depends_on:
      - api
      - database
    env_file:
      - .env
    build:
      context: api
      dockerfile: Dockerfile.view
