services:
  db:
    image: postgres:14.4
    restart: always
    environment:
      POSTGRES_USER: example
      POSTGRES_PASSWORD: example
      POSTGRES_DB: database
    volumes:
      - /ESGdata:/var/lib/postgresql/data
    ports:
      - "5432:5432"

  selenium:
    image: selenium/standalone-firefox
    ports:
    - 4444:4444

  grafana:
    image: grafana/grafana:8.2.6
    ports:
      - 3000:3000
    user: ":"
    volumes:
    - /grafana:/var/lib/grafana

  script:
    depends_on:
      - db
      - grafana
      - selenium
    build: .
    environment:
      CONNECTION: "postgresql+psycopg2://example:example@db/database"
      DOCKER: "true"
    volumes:
      - ./pretrained_models:/app/pretrained_models
