services:
  database:
    image: postgres:14.4
    restart: always
    env_file:
      - ./.env
    ports:
      - 5432:5432

  tests:
    depends_on:
      - database
    env_file:
      - ./.env
    build: .
    ports:
      - 8000:8000
